# Generated by Django 4.2.11 on 2024-04-23 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dreams",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.CharField(default="", max_length=45)),
                (
                    "submission_time",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=200)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+10000000000", max_length=128, region=None
                    ),
                ),
                (
                    "mbti_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("INTJ", "INTJ"),
                            ("INTP", "INTP"),
                            ("ENTJ", "ENTJ"),
                            ("ENTP", "ENTP"),
                            ("INFJ", "INFJ"),
                            ("INFP", "INFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENFP", "ENFP"),
                            ("ISTJ", "ISTJ"),
                            ("ISFJ", "ISFJ"),
                            ("ESTJ", "ESTJ"),
                            ("ESFJ", "ESFJ"),
                            ("ISTP", "ISTP"),
                            ("ISFP", "ISFP"),
                            ("ESTP", "ESTP"),
                            ("ESFP", "ESFP"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                (
                    "pub",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="date published"
                    ),
                ),
                ("title", models.CharField(max_length=44)),
                ("dream", models.TextField(default="")),
                ("viewobj", models.IntegerField(default=0)),
                ("timer", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "dreams",
                "ordering": ["-pub"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="R", max_length=50)),
                ("reply", models.TextField()),
                ("pub", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dreams"
                    ),
                ),
            ],
        ),
    ]
