# Generated by Django 4.2.11 on 2024-05-24 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreams",
            name="pub",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="dreams",
            name="submission_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
