# Generated by Django 4.2.11 on 2024-06-05 11:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_dreams_pub_alter_dreams_submission_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.CharField(default="", max_length=45)),
                (
                    "submission_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user", models.CharField(default="", max_length=50)),
                (
                    "pub",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                ("title", models.CharField(max_length=44)),
                ("dream", models.TextField(default="")),
            ],
            options={
                "verbose_name": "share",
                "ordering": ["-pub"],
            },
        ),
    ]
