# Generated by Django 4.2.11 on 2024-06-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_share"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dreams",
            name="phone",
        ),
    ]
