# Generated by Django 4.2.11 on 2024-06-11 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_dreams_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreams",
            name="scale",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
