# Generated by Django 4.2.11 on 2024-06-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_dreams_scale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dreams",
            name="scale",
        ),
    ]
