# Generated by Django 4.2.11 on 2024-06-22 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_dreams_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreams",
            name="scale",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
